### PR TITLE
Added wiki and stl files

### PR DESCRIPTION
**Pull request by psonnera**
I would like to deprecate the pdf in order to give access to the install guides for those not with Facebook and make it easier to read them with an automated translator.
Bases stl are included, I can try to get authors written consent if you wish.

### CODE REVIEW

**Comment by psonnera** [comment]
Can't PR the wiki and it didn't merge automatically. https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github That's a real shame as it was very simple. What do you think is easier? Add .md pages to the project and put the images in https://github.com/mlukasek/M5_NightscoutMon/tree/master/images ? Else you need to do it manually git clone https://github.com/mlukasek/M5_NightscoutMon.wiki.git then https://github.com/psonnera/M5_NightscoutMon.wiki.git then copy one to the other and commit yours...

**Comment by mlukasek** [comment]
Hi Patrick, I aded you as a colaborator, so you should have a write access now.

**Comment by psonnera** [comment]
Great, Updated. Thanks!

**Comment by mlukasek** [comment]
It would be great to link Wiki from the main paga ant put some basic info there. What do you think?

**Comment by mlukasek** [comment]
And great work with the guides btw! Very useful! Thank you!

**Comment by psonnera** [comment]
@mlukasek yes this is just a starting point, will add more from the group knowledge.

**Comment by mlukasek** [comment]
Great, thank you very much for taking care of it!

**Pull request merged**
