### PR TITLE
correcting the display of the delta in the form of 0.1 when cfg in 'mmol'

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mlukasek** [comment]
Hi,

I am not sure about the change. What is the difference? It will display the same delta as before, just taken form another json part.

Best regards

Martin

**Comment by ghost** [comment]
Hi. If the variable in Nightscout is set to mg dl, then on M5 delta always shows in mg dl, even if you set mmol in the M5 settings

**Comment by mlukasek** [comment]
Ok, I understand, bu why would you setup your Nightscout in mgdl and M5Stack in mmol? I was quite in opposite to this considering to omit some parameteres from M5NS.INI and take it from Nightscout for easier setup.

**Comment by ghost** [comment]
I was a little imprecise. I was referring to setting up heroku variables. I agree with You that it is more correct to take settings from Nightscout. However, in Nightscout itself, even if the variable settings in Heroku are set to mg dl, if the user selects mol, everything is displayed correctly on the screen. But in json in this case goes mg and M5 sugar shows in mmol, and delta in mgdl.

You know best, of course. But I am faced with the fact that users cannot change Heroku variables and in this case M5 does not work correctly.

**Comment by mlukasek** [comment]
Ok

**Pull request merged**
